server:
  port: 8899
  context-path: /userauth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  application:
      name: zxc-auth
  datasource:
      url: jdbc:mysql://localhost:3306/zxc_auth?characterEncoding=UTF-8&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      initialize: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700
  user-datasource:
      url: jdbc:mysql://localhost:3306/zxc_auth?characterEncoding=UTF-8&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      initialize: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

liquibase:
   enabled: true
   check-change-log-location: true
   change-log: classpath:/liquibase/db.changelog.xml