server:
  port: 8899
  context-path: /userauth
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.227.10:1111/eureka/
  instance:
      prefer-ip-address: true

spring:
  application:
      name: zxc-auth
  datasource:
      url: jdbc:mysql://192.168.227.10:3306/zxc_user?characterEncoding=UTF-8&useSSL=false
      username: root
      password: zxc@0405
      driver-class-name: com.mysql.jdbc.Driver
      initialize: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        hibernate:
          current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  thymeleaf:
      content-type: application/xhtml+xml
  security:
      user:
        password: password
      oauth2:
        resource:
          userInfoUri:  http://192.168.227.10:8899/userauth/me
          preferTokenInfo:  false
        sso:
          home:
            path: /,/**/*.html
            secure: false
        client:
          accessTokenUri: http://192.168.227.10:8899/userauth/oauth/token
          userAuthorizationUri: http://192.168.227.10:8899/userauth/oauth/authorize
          clientId: client
          clientSecret: secret
      loginSecret:  puffing007

liquibase:
   enabled: true
   check-change-log-location: true
   change-log: classpath:/liquibase/db.changelog.xml